<?xml version="1.0" ?>
<testsuite errors="2" failures="0" name="tests.hfmagpsu.HfmagpsuTests-20170822102228" tests="2" time="22.003">
	<testcase classname="tests.hfmagpsu.HfmagpsuTests" name="test_GIVEN_direction_set_WHEN_read_THEN_direction_is_as_expected" time="9.547">
		<error message="invalid literal for int() with base 10: '+'" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\tests\hfmagpsu.py", line 95, in test_GIVEN_direction_set_WHEN_read_THEN_direction_is_as_expected
    self._write_direction('+')
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\tests\hfmagpsu.py", line 17, in _write_direction
    self.ca.set_pv_value("HFMAGPSU_01:DIRECTION:SP", direction)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 40, in set_pv_value
    self.ca.set_pv_value(self._create_pv_with_prefix(pv), value, wait=True, timeout=None)
  File "C:\Instrument\Apps\Python\lib\site-packages\genie_python\genie_cachannel_wrapper.py", line 44, in set_pv_value
    chan.array_put_callback(value, ftype, ecount, CaChannelWrapper.putCB, event)
  File "C:\Instrument\Apps\Python\lib\site-packages\CaChannel.py", line 347, in array_put_callback
    val = self._setup_put(value, req_type, count)
  File "C:\Instrument\Apps\Python\lib\site-packages\CaChannel.py", line 246, in _setup_put
    pval = (CaChannel.dbr_d[req_type](value),)
ValueError: invalid literal for int() with base 10: '+'
]]>		</error>
	</testcase>
	<testcase classname="tests.hfmagpsu.HfmagpsuTests" name="test_GIVEN_rampTarget_set_WHEN_read_THEN_rampTarget_is_as_expected" time="12.456">
		<error message="Values didn't match when reading PV 'HFMAGPSU_01:RAMPTARGET'.
                   Expected value: MID
                   Actual value: " type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\tests\hfmagpsu.py", line 102, in test_GIVEN_rampTarget_set_WHEN_read_THEN_rampTarget_is_as_expected
    self.ca.assert_that_pv_is("HFMAGPSU_01:RAMPTARGET", expected_rampTarget)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 68, in assert_that_pv_is
    raise AssertionError(error_message)
AssertionError: Values didn't match when reading PV 'HFMAGPSU_01:RAMPTARGET'.
                   Expected value: MID
                   Actual value: 
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
