<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="tests.hfmagpsu.HfmagpsuTests-20170822151236" tests="1" time="20.767">
	<testcase classname="tests.hfmagpsu.HfmagpsuTests" name="test_GIVEN_rampTarget_set_WHEN_read_THEN_rampTarget_is_as_expected" time="20.767">
		<error message="Values didn't match when reading PV 'HFMAGPSU_01:RAMPTARGET'.
                   Expected value: MAX
                   Actual value: ZERO" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\tests\hfmagpsu.py", line 122, in test_GIVEN_rampTarget_set_WHEN_read_THEN_rampTarget_is_as_expected
    self.ca.assert_that_pv_is("HFMAGPSU_01:RAMPTARGET", expected_rampTarget)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 68, in assert_that_pv_is
    raise AssertionError(error_message)
AssertionError: Values didn't match when reading PV 'HFMAGPSU_01:RAMPTARGET'.
                   Expected value: MAX
                   Actual value: ZERO
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
